apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  description: 'Bye Tekton'
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        set -e
        echo "Goodbye Tekton!"
